# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# Android settings
android.useAndroidX=true
android.nonTransitiveRClass=true

# Annotation Processor
org.gradle.configureondemand=false

# Use system build-tools aapt2 (QEMU-wrapped) instead of AGP embedded x86_64
android.aapt2FromMavenOverride=/root/Android/build-tools/34.0.0/aapt2
